# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.giggles.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'giggles', 'function_path': 'animated_java:giggles/variants/default/apply'}
execute on passengers if entity @s[tag=aj.giggles.bone.lower_tentical_ul2] run function animated_java:giggles/variants/default/zzz/0
execute on passengers if entity @s[tag=aj.giggles.bone.tentical_dl] run function animated_java:giggles/variants/default/zzz/1
execute on passengers if entity @s[tag=aj.giggles.bone.lower_tentical_ul] run function animated_java:giggles/variants/default/zzz/2
execute on passengers if entity @s[tag=aj.giggles.bone.tentical_ul] run function animated_java:giggles/variants/default/zzz/3
execute on passengers if entity @s[tag=aj.giggles.bone.upper_head] run function animated_java:giggles/variants/default/zzz/4
execute on passengers if entity @s[tag=aj.giggles.bone.lower_tentical_dr] run function animated_java:giggles/variants/default/zzz/5
execute on passengers if entity @s[tag=aj.giggles.bone.tentical_dr] run function animated_java:giggles/variants/default/zzz/6
execute on passengers if entity @s[tag=aj.giggles.bone.lower_tentical_dl] run function animated_java:giggles/variants/default/zzz/7
execute on passengers if entity @s[tag=aj.giggles.bone.tentical_dl2] run function animated_java:giggles/variants/default/zzz/8
execute on passengers if entity @s[tag=aj.giggles.bone.lower_head] run function animated_java:giggles/variants/default/zzz/9
execute on passengers if entity @s[tag=aj.giggles.bone.bone] run function animated_java:giggles/variants/default/zzz/10
execute on passengers if entity @s[tag=aj.giggles.bone.crucifix] run function animated_java:giggles/variants/default/zzz/11
execute on passengers if entity @s[tag=aj.giggles.bone.test] run function animated_java:giggles/variants/default/zzz/12
execute on passengers if entity @s[tag=aj.giggles.bone.crucifix_white] run function animated_java:giggles/variants/default/zzz/13
execute on passengers if entity @s[tag=aj.giggles.bone.crucifix_blue] run function animated_java:giggles/variants/default/zzz/14
execute on passengers if entity @s[tag=aj.giggles.bone.clockwise] run function animated_java:giggles/variants/default/zzz/15
execute on passengers if entity @s[tag=aj.giggles.bone.counterclockwise] run function animated_java:giggles/variants/default/zzz/16
execute on passengers if entity @s[tag=aj.giggles.bone.chain5] run function animated_java:giggles/variants/default/zzz/17
execute on passengers if entity @s[tag=aj.giggles.bone.chain3] run function animated_java:giggles/variants/default/zzz/18
execute on passengers if entity @s[tag=aj.giggles.bone.chain6] run function animated_java:giggles/variants/default/zzz/19
execute on passengers if entity @s[tag=aj.giggles.bone.chain2] run function animated_java:giggles/variants/default/zzz/20
execute on passengers if entity @s[tag=aj.giggles.bone.chain4] run function animated_java:giggles/variants/default/zzz/21
execute on passengers if entity @s[tag=aj.giggles.bone.chain7] run function animated_java:giggles/variants/default/zzz/22
execute on passengers if entity @s[tag=aj.giggles.bone.light_beam] run function animated_java:giggles/variants/default/zzz/23