# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on vehicle unless entity @s[tag=aj.transforms_only] positioned ^0 ^2.0625 ^-2.125 rotated ~0 ~0 run function animated_java:crucifix/animations/crucifix/zzz/frames/zzz/95
data modify entity @s data merge value {"locators":{"entity":{"posx":0.06249999999999999,"posy":-3.53126375,"posz":0.04062459375000001,"roty":0,"rotx":0}},"cameras":{}}
execute on vehicle unless entity @s[tag=aj.transforms_only] at @s run function animated_java:crucifix/animations/crucifix/zzz/frames/zzz/96