# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
playsound doorsentities:item.crucifix.fail hostile @a[distance=..32] ~ ~ ~ 5
setblock ~ ~0.2 ~ light[level=12]