# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute as @e[tag=crucifix.locator.entity] run tag @s add crucifix.unmountpassengers
setblock ~ ~0.2 ~ air