# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.giggles.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'giggles', 'function_path': 'animated_java:giggles/animations/giggles/next_frame'}
execute if score @s aj.giggles.frame matches 18.. run scoreboard players set @s aj.giggles.frame 1
execute store result storage aj:temp frame int 1 run scoreboard players get @s aj.giggles.frame
execute at @s run function animated_java:giggles/animations/giggles/zzz/apply_frame with storage aj:temp
scoreboard players add @s aj.giggles.frame 1