# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.crucifix.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'crucifix', 'function_path': 'animated_java:crucifix/variants/fail/apply'}
execute on passengers if entity @s[tag=aj.crucifix.bone.crucifix] run function animated_java:crucifix/variants/fail/zzz/0
execute on passengers if entity @s[tag=aj.crucifix.bone.test] run function animated_java:crucifix/variants/fail/zzz/1
execute on passengers if entity @s[tag=aj.crucifix.bone.crucifix_white] run function animated_java:crucifix/variants/fail/zzz/2
execute on passengers if entity @s[tag=aj.crucifix.bone.crucifix_blue] run function animated_java:crucifix/variants/fail/zzz/3
execute on passengers if entity @s[tag=aj.crucifix.bone.clockwise] run function animated_java:crucifix/variants/fail/zzz/4
execute on passengers if entity @s[tag=aj.crucifix.bone.counterclockwise] run function animated_java:crucifix/variants/fail/zzz/5
execute on passengers if entity @s[tag=aj.crucifix.bone.chain5] run function animated_java:crucifix/variants/fail/zzz/6
execute on passengers if entity @s[tag=aj.crucifix.bone.chain3] run function animated_java:crucifix/variants/fail/zzz/7
execute on passengers if entity @s[tag=aj.crucifix.bone.chain6] run function animated_java:crucifix/variants/fail/zzz/8
execute on passengers if entity @s[tag=aj.crucifix.bone.chain2] run function animated_java:crucifix/variants/fail/zzz/9
execute on passengers if entity @s[tag=aj.crucifix.bone.chain4] run function animated_java:crucifix/variants/fail/zzz/10
execute on passengers if entity @s[tag=aj.crucifix.bone.chain7] run function animated_java:crucifix/variants/fail/zzz/11
execute on passengers if entity @s[tag=aj.crucifix.bone.light_beam] run function animated_java:crucifix/variants/fail/zzz/12