# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.crucifix.root] run return 0
execute on passengers if entity @s[tag=aj.crucifix.data] unless data entity @s {data:{rigHash: 'e3b5dcc04a39d4e856b7fa7d5d51f6acf13fa37738430ec2ecdb46988255ac8d'}} on vehicle run function animated_java:crucifix/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1