# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.giggles.root] run return 0
execute unless score @s aj.is_rig_loaded matches 1 run function #animated_java:global/root/on_load
function #animated_java:giggles/as_root/pre_tick
execute if entity @s[tag=aj.giggles.animation.giggles.playing] run function animated_java:giggles/animations/giggles/zzz/on_tick
execute if entity @s[tag=aj.giggles.animation.hanging.playing] run function animated_java:giggles/animations/hanging/zzz/on_tick
execute if entity @s[tag=aj.giggles.animation.prefall.playing] run function animated_java:giggles/animations/prefall/zzz/on_tick
execute if entity @s[tag=aj.giggles.animation.falling.playing] run function animated_java:giggles/animations/falling/zzz/on_tick
execute if entity @s[tag=aj.giggles.animation.falling_fail.playing] run function animated_java:giggles/animations/falling_fail/zzz/on_tick
execute if entity @s[tag=aj.giggles.animation.land.playing] run function animated_java:giggles/animations/land/zzz/on_tick
execute if entity @s[tag=aj.giggles.animation.die.playing] run function animated_java:giggles/animations/die/zzz/on_tick
execute if entity @s[tag=aj.giggles.animation.stun.playing] run function animated_java:giggles/animations/stun/zzz/on_tick
execute if entity @s[tag=aj.giggles.animation.crucifix.playing] run function animated_java:giggles/animations/crucifix/zzz/on_tick
execute on passengers if entity @s[tag=aj.giggles.data] run function animated_java:giggles/root/zzz/1
execute at @s on passengers run tp @s ~ ~ ~ ~ ~
function #animated_java:giggles/as_root/post_tick