# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:giggles/animations/falling/zzz/apply_frame {frame: 10}
scoreboard players add @s aj.falling.frame 1