# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:giggles/animations/land/zzz/apply_frame {frame: 15}
scoreboard players add @s aj.land.frame 1