# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.crucifix.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'crucifix', 'function_path': 'animated_java:crucifix/animations/crucifix_fail/next_frame'}
execute if score @s aj.crucifix_fail.frame matches 196.. run scoreboard players set @s aj.crucifix_fail.frame 1
execute store result storage aj:temp frame int 1 run scoreboard players get @s aj.crucifix_fail.frame
execute at @s run function animated_java:crucifix/animations/crucifix_fail/zzz/apply_frame with storage aj:temp
scoreboard players add @s aj.crucifix_fail.frame 1