# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.crucifix.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'crucifix', 'function_path': 'animated_java:crucifix/animations/crucifix_fail/stop'}
tag @s remove aj.crucifix.animation.crucifix_fail.playing
scoreboard players set @s aj.crucifix_fail.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:crucifix/animations/crucifix_fail/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only