# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.data_data set from storage aj:uuid main.out
summon minecraft:armor_stand ~ ~ ~ {Tags:['aj.new', 'aj.locator', 'aj.crucifix.locator', 'aj.crucifix.locator.entity']}
execute as @e[type=minecraft:armor_stand,tag=aj.new,tag=aj.locator,limit=1,distance=..0.01] run function animated_java:crucifix/zzz/2
data modify entity @s data.locators.entity.uuid set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.crucifix.bone.crucifix] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_crucifix set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.crucifix.bone.test] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_test set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.crucifix.bone.crucifix_white] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_crucifix_white set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.crucifix.bone.crucifix_blue] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_crucifix_blue set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.crucifix.bone.clockwise] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_clockwise set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.crucifix.bone.counterclockwise] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_counterclockwise set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.crucifix.bone.chain5] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_chain5 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.crucifix.bone.chain3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_chain3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.crucifix.bone.chain6] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_chain6 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.crucifix.bone.chain2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_chain2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.crucifix.bone.chain4] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_chain4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.crucifix.bone.chain7] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_chain7 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.crucifix.bone.light_beam] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_light_beam set from storage aj:uuid main.out