# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage aj:temp uuid set from entity @s data.locators.crucifix.uuid
function animated_java:crucifix/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.entity.uuid
function animated_java:crucifix/zzz/execute with storage aj:temp